### ISSUE TITLE
Wumiibo doesn't work and service is not running

### ISSUE THREAD

**Issue by AyraHikari** [hax0kartik/wumiibo#29]
A few days ago it working well, last time using it crash the game until i didn't using it for some days

After installed Fire Emblem Echoes (undub), DLC and Update, i did trying to do wumiibo

But it doesn't work, service is not running

![Photo](https://telegra.ph/file/b8ba84a7b8a8dc1fa30f4.jpg)
> I did check 'game patching' already turned on in latest Luma3DS
- i did uncheck and save, power off
- booting and turn on game patching again, still doesn't work

![Photo](https://telegra.ph/file/5a967019d6c81b2541746.jpg)
> The files already there untouched
- i did delete the folder, and copy files again, still doesn't work

![Photo](https://telegra.ph/file/4c4b24f249e9f48674d72.jpg)
> Checked list running, there is no wumiibo in there

![Photo](https://telegra.ph/file/65a90e9a4e24156cc93e7.jpg)
> Checked in Fire Emblem Echoes, there is nfc in process list, but no wumiibo

Also my wumiibo dir in sdcard is just 'Fire Emblem' folder with 5 bin files inside

**Comment by redunka-zver** [comment]
Your first screenshot shows that your Luma boots from CTRNAND.
By design Luma CFW looks for its files (config, payloads, patched files, etc) in the same location that the CFW itself boots from.
So you can technically make it work by moving "0004013000004002" folder to "CTRNAND:/rw/luma/titles", but if you want to properly load wumiibo module from SD, you'd have to make sure that Luma also loads from SD.

**Comment by AyraHikari** [comment]
Thanks, i did moved titles to CTRNAND, now its working
