### ISSUE TITLE
Hey Pikmin! and Mario and Luigi Paper Jam do not work

### ISSUE THREAD

**Issue by hax0kartik** [hax0kartik/wumiibo#5]

**Comment by hax0kartik** [comment]
Hey Pikmin seems to have been fixed by commit b6593753f024d7b785f10e7641cff7d2ff94a602

**Comment by RinMaru** [comment]
Olimar works but Pikmin amiibo doesnt it will say "Cant upgrade this Amiibo only pikmin amiibo can be leveled up"

**Comment by Unfriended** [comment]
I had this issue in Paper Jam as well, but it turns out that you need the amiibo held down in the NFC Reader/Writer in order to create the character set and to make a ? card as well, so please have the option to have the amiibo held down on the NFC Reader/Writer and the option to take it off the NFC Reader/Writer

**Comment by hax0kartik** [comment]
Heya, this issue is fixed in the latest commit, I still have to make a release.
